name: Release

on:
    workflow_dispatch:
    push:
        tags:
            - 'v*'
        # branches:
        #     - 'main'

jobs:
    publish-tauri:
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                include:
                    - platform: 'windows-latest'
                      target: 'x86_64-pc-windows-msvc'
                      args: ''

        runs-on: ${{ matrix.platform }}
        timeout-minutes: 60
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Install rust target
              run: rustup target add ${{ matrix.target }}

            - uses: pnpm/action-setup@v3
              with:
                  version: latest

            - name: Sync node version and setup cache
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm

            - name: Install frontend dependencies
              run: pnpm install

            - name: install Rust stable
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: ${{ matrix.target }}

            - name: Regenerate Icons
              run: pnpm tauri icon

            - name: Init Project Config
              run: node ./scripts/ppworker.cjs

            - name: install dependencies (ubuntu only)
              if: matrix.platform == 'ubuntu-22.04'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

            - uses: Sjj1024/tauri-zhaction@tauri-zhaciton
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NAME: ${{ env.NAME }}
                  VERSION: ${{ env.VERSION }}
                  PUBBODY: ${{ env.PUBBODY }}
              with:
                  tagName: '${{ env.NAME }}'
                  releaseName: '${{ env.NAME }} v${{ env.VERSION }}'
                  releaseBody: '${{ env.PUBBODY }}'
                  releaseDraft: false
                  prerelease: false
                  args: ${{ matrix.args }}
                  renameArtifacts: '${{ env.NAME }}'
